-- Documents the `projects` table (one row per concrete project instance —
-- a specific concert, a specific release, etc.) so its schema lives in the
-- repo like every other table's does. This table already exists in the
-- live Supabase database — it was created by hand through the dashboard
-- while building the Concert feature, with no matching migration checked
-- in. `CREATE TABLE IF NOT EXISTS` makes this safe to run against that
-- existing table: it's a no-op if the table is already there.
--
-- Run this once in the Supabase SQL Editor.
--
-- NOTE: `bands` itself also has no committed CREATE TABLE in this repo
-- (only migration_band_profile.sql's ALTER on top of it). The FK below
-- assumes bands.id is `uuid`, matching Supabase's usual default for a
-- table's id column — if your SQL Editor run errors on the FK line,
-- check Table Editor → bands → id column's type and adjust `uuid` below
-- to match.

create table if not exists projects (
  id bigint generated by default as identity primary key,
  band_id uuid not null references bands(id),
  project_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- details is intentionally free-form per project_type (informal shape,
-- not enforced by Postgres, same pattern as bands.profile in
-- migration_band_profile.sql). Example for project_type = 'concert':
-- {"ticket_owner": "manager" | "venue", "is_paid": true}
